### ISSUE TITLE
Error: No Description or ProductDescription provided

### ISSUE THREAD

**Issue by shivarajnaidu** [electron-userland/electron-installer-debian#148]
**What version of `electron-installer-debian` are you using?**
1.0.0

**What version of `node` and `npm` are you using?**
node - v8.12.0 and npm 6.4.1

**What operating system are you using?**
KUBUNTU 18.04

**What did you expect to happen?**
expecting to build .deb properly without any issue with given instructions

**What actually happened?**
when I run this.. `electron-installer-debian --src build/app-linux-x64/ --dest build/installers/ --arch amd64` getting this error..
```
electron-installer-debian --src build/app-linux-x64/ --dest build/installers/ --arch amd64
Creating package (this may take a while)
Error: No Description or ProductDescription provided
    at getOptions (/home/shivaraj/.nvm/versions/node/v8.12.0/lib/node_modules/electron-installer-debian/src/installer.js:156:11)
    at getDefaults.then.defaults (/home/shivaraj/.nvm/versions/node/v8.12.0/lib/node_modules/electron-installer-debian/src/installer.js:430:23)
    at <anonymous> 'Error: No Description or ProductDescription provided\n    at getOptions (/home/shivaraj/.nvm/versions/node/v8.12.0/lib/node_modules/electron-installer-debian/src/installer.js:156:11)\n    at getDefaults.then.defaults (/home/shivaraj/.nvm/versions/node/v8.12.0/lib/node_modules/electron-installer-debian/src/installer.js:430:23)\n    at <anonymous>'
```

**Comment by fcastilloec** [comment]
This is not an bug/issue. As the error says, you need at least a `description` in order to build. You can either pass it as an option (see [options.descritpion](https://github.com/electron-userland/electron-installer-debian#optionsdescription)) or the easiest way is to add a description to your `package.json`

**Comment by shivarajnaidu** [comment]
Sorry..  And Thank You For Your Quick Reply..

And I've one suggestion.
Please add some note about these mandatory things in docs.. Will be helpful for new people..

Thank You :)

**Comment by torressam333** [comment]
Note: If you are initially missing your description in your package.json and you add one after getting this error AND you already ran `npm run package-linux` then you must delete the `release-builds` directory and re-package the electron app and then you can run the debian installer command.

**Comment by stewpidtnlvr** [comment]
> Note: If you are initially missing your description in your package.json and you add one after getting this error AND you already ran `npm run package-linux` then you must delete the `release-builds` directory and re-package the electron app and then you can run the debian installer command.

where is the release-builds directory?
