### ISSUE TITLE
Array options need to be explicitly configured in yargs declaration

### ISSUE THREAD

**Issue by cellard0or** [electron-userland/electron-installer-debian#154]
**What version of `electron-installer-debian` are you using?**
1.0.0

When using e.g.
`electron-installer-debian --options.depends "['testDep']"`
it has no effect on the dependencies of the resulting package. Specifying it via a config file works fine, though.
I suspect I am using wrong syntax to specify the expected Array[String]. Documentation does not say anything about the syntax, maybe you can help me with that?

**Comment by malept** [comment]
It should just be `--options.depends=testDep`.

**Comment by cellard0or** [comment]
Thanks for the tip!
Unfortunately, `--options.depends=testDep` does not work either. The example in your yargs link (`--options.depends testDep testDep2`) does not work as well. Package information still only contains default values for `Depends:`. This is odd because the other options like options.name or bin work just fine.

**Comment by malept** [comment]
I think this is a quirk in the lack of types for yargs. Arrays need to be explicitly specified.

**Comment by fcastilloec** [comment]
@cellard0or yargs can create an array if you specify the options multiple time, i.e. `--options.depends=testDep --options.depends testDep2`. If you have only a single dependency to add, as a workaround you can pass the same dependency twice, so it'll be passed as an array and `electron-installer-debian` will remove any duplicates from the array, so it will still work.

I don't have a lot of time right now, but I'll try to fix this soon by parsing arrays with yargs for the options that requiere them
