### ISSUE TITLE
Confusion About LICENSE/copyright Files (Question)

### ISSUE THREAD

**Issue by cellard0or** [electron-userland/electron-installer-debian#157]
**What version of `electron-installer-debian` are you using?**
1.0.0

**What version of `node` and `npm` are you using?**
npm - 6.4.1, node - 8.12.0

**What operating system are you using?**
Ubuntu 18.04

This is more of a question: When examining the resulting Debian package, I observed, that the original LICENSE was not copied into the package (LICENSES.chromium.html is there, though). Is this expected? In the `electron-packager` intermediate directory, the file is still there.

Interestingly, a `/usr/share/doc/<appName>/copyright` can be found in the package, which, to my knowledge, is not part of my repository. The content of that file is `Copyright (c) 2013-2017 GitHub Inc.` and so on. Where does this come from? In the `electron-packager` intermediate directory, this file is also not included.

**Comment by malept** [comment]
The Electron license is moved from the app root directory to `/usr/share/doc/<appName>/copyright`.
