### ISSUE TITLE
the .deb package for armv7l

### ISSUE THREAD

**Issue by e404r** [electron-userland/electron-installer-debian#195]
Hi, when installing the .deb package for armv7l, on a raspberry PI 3 I got the following error:
package architecture (armv7l) does not match system (armhf),
Thank you

**Comment by malept** [comment]
Please fill out the [issue template](https://raw.githubusercontent.com/electron-userland/electron-installer-debian/master/.github/ISSUE_TEMPLATE.md) and paste the answers in the issue summary. As your summary is currently written, there is not enough information to give any sort of advice.

**Comment by fcastilloec** [comment]
@e404r As mentioned we need more information to help you. What's the output of the command `uname -a` on your raspberry PI 3? From what I understand `armv7l` is the version of your processor architecture but that doesn't mean that your OS matches that version.
Just a quick googling/wikipedia you can find this (https://en.wikipedia.org/wiki/ARM_architecture#VFP):

> armhf (ARM hard float) refers to the ARMv7 architecture including the additional VFP3-D16 floating-point hardware extension (and Thumb-2) above

You should create the .deb with `--arch armhf` (or using a config file) as specified in https://github.com/electron-userland/electron-installer-debian#optionsarch and make sure that the OS where you're building supports the architecture by running `dpkg-architecture -L` which is mentioned in the README.
In fact, in my Ubuntu system, there's no such thing as `armv7l` architecture

**Comment by e404r** [comment]
thanks,   I do not know why impacted  sudo dpkg -i debfile.deb but sudo apt-get install 'debfile.deb'  works for me

**Comment by malept** [comment]
It impacted installing the deb file because the deb file was created incorrectly.

**Comment by e404r** [comment]
> It impacted installing the deb file because the deb file was created incorrectly. I suspect `dpkg` has stronger validations for some reason.
my script is:

  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "electron-packager . term --platform linux --arch armv7l --overwrite --out distrp/",
    "deb64": "electron-installer-debian --src distrp/term-linux-armv7l/ --dest distrp/installers/ --arch armv7l"
  },

**Comment by malept** [comment]
Yes, it should be `--arch armhf` because Debian uses `armhf`, but Node uses `armv7l`.

**Comment by e404r** [comment]
> Yes, it should be `--arch armhf` because Debian uses `armhf`, but Node uses `armv7l`.

"build":  section not supported armhf.

"deb64": armhf  working  but after install app not opening , app in the windows and Linux-lite Works perfect but pi3b  not working

**Comment by malept** [comment]
> "build": section not supported armhf.

Yes, because Electron Packager is not Debian specific, it uses Node-style arch names as that's what Electron itself uses in its download file names.

To be clear, you need to specify `--arch=armv7l` for `electron-packager` and `--arch=armhf` for `electron-installer-debian`.

**Comment by malept** [comment]
> armhf working but after install app not opening , app in the windows and Linux-lite Works perfect but pi3b not working

If it doesn't run, it's not the fault of electron-installer-debian. You're probably running into an [Electron bug](https://github.com/electron/electron/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+raspberry+pi).

**Comment by e404r** [comment]
all working perfectly wen i used electron js v1.7.0

**Comment by malept** [comment]
Yes, this is absolutely one of the Electron bugs I linked in my previous comment.
