### ISSUE TITLE
High Security Vulnerability in Lodash 4.17.11

### ISSUE THREAD

**Issue by kunalnagar** [electron-userland/electron-installer-debian#205]
**What version of `electron-installer-debian` are you using?**
v2.0.0

**What version of `node` and `npm` are you using?**
node - v10.16.0
npm - 6.9.0

**What operating system are you using?**
macOS High Sierra

There is a high security vulnerability in Lodash 4.17.11 that is being used by this package. I've opened this issue to track an update to this package once the Lodash issue is fixed.

Details: https://github.com/lodash/lodash/issues/4348
Snyk Report: https://app.snyk.io/vuln/SNYK-JS-LODASH-450202

Once the Lodash patch is released, could you please update the package dependency here as well? Thanks!

**Comment by malept** [comment]
The dependency isn't a fixed version:

https://github.com/electron-userland/electron-installer-debian/blob/74b5e415fe0aaf6b00b2cb2c9cd982ed6c325f22/package.json#L40

Once it is released upstream, all you need to do is `npm update` or `yarn upgrade` yourself.

**Comment by kunalnagar** [comment]
@malept thanks for the update - lodash 4.7.12 has been released which should fix this. Closing for now.
