### ISSUE TITLE
Remove dependency on libgconf2-4 in favor of libgconf-2-4 for compatibility

### ISSUE THREAD

**Issue by credmp** [electron-userland/electron-installer-debian#222]
The below contents is from #141. Ubuntu has removed the meta package libgconf2-4 in favor of the actual package libgconf-2-4 (notice the dash). As a result none of the packages built with electron-installer-debian will install on recent Ubuntu installations. #141 was closed without a solution as a result.

**What version of `electron-installer-debian` are you using?**
0.8.1
**What version of `node` and `npm` are you using?**
v6.11.3 and 3.10.10
**What operating system are you using?**

    * To compile, Linux Mint 18.1 Mate 64bits
 
    * To install the .deb, Huayra Linux 64 bits, based on Debian 8.3 and Mate 1.8.1
 
 
**Can you compile the [example app](https://github.com/unindented/electron-installer-debian/tree/master/example) successfully?**
 yes
 
**What did you do? Please include the configuration you are using for `electron-installer-debian`.**
 In Linux Mint:
 
     * `electron-installer-debian --src (my source) --dest (my dest) --arch amd64`
 
 
 In Huayra:
 
     * I double click the .deb. I answer "Yes" to "Do you want to install this package". After starting the unpackaging process, it says  (In spanish) "Failure when installing".
 
     * I then tried a `sudo dpkg -i` and says that it has unmet dependencies with "libgconf2-4", yet however **I do have installed the package libgconf-2-4** (note the extra hyphen). [Here](https://packages.debian.org/sid/libgconf2-4) it says that libgconf2-4 is a _dummy package_, so I think that every repository that has libgconf2-4 also has libgconf-2-4, but it's not the case in the other way (In Huayra repositories they only have the libgconf-2-4 package, which is exactly the same).
 
 
**What did you expect to happen?**
I expected to be able to install the .deb package in debian.
 
**What actually happened?**
 It didn't.

**Comment by malept** [comment]
Your version of `electron-installer-debian` is very out of date. Please use the newest version.

**Comment by credmp** [comment]
Indeed, the project I was using is indeed reliant on an old version. This issue was fixed with https://github.com/electron-userland/electron-installer-debian/pull/185.
