### ISSUE TITLE
compiled app for ubuntu won't run

### ISSUE THREAD

**Issue by jcalcada-atoswap** [electron-userland/electron-installer-debian#226]
Hi,
My compiled app don't run and i don't know why ...

- electron-installer-debian -> 3.0.0
- node -> 8.16.0
- npm -> 6.4.1
- operating system ->ubuntu 16.04.6 amd64

- I can compile the example app successfully.
- I can compile my app successfully.

**What did i do**

`package.json content`
> {
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "build": "electron-packager . electron-quick-start --platform linux --arch x64 --out dist/",
    "deb64": "electron-installer-debian --src dist/electron-quick-start-linux-x64/ --dest dist/installers/ --arch amd64"
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^8.2.5",
    "electron-installer-debian": "^3.0.0",
    "electron-packager": "^14.2.1"
  }
}

I compile my app successfullt by executing `npm run build` to build my app with electron-packager then i do `npm run deb64` to compile my code.
It return a successfull sentence.

Then i find my `electron-quick-start_1.0.0_amd64.deb` in the `dist/installers` folder and install it successfully (no error of any kind).

**What did you expect to happen?**
I expect to run my app by searching it in the ubuntu search bar.

**What actually happened?**
The app juste don't run. No error pop up. Nothing ... :'(

**Comment by fcastilloec** [comment]
I'm sorry but I can't reproduce this. I have VM with Ubuntu 16.04 where I've cloned the `electron-quick-start` repo, use the same `node` and `npm` versions, run your exact commands and everything is working without a problem. I can search for the packages on the search bar and I see this, which can run without issues:
![Selection_001](https://user-images.githubusercontent.com/1280530/80879806-d79f7980-8c70-11ea-9d1c-243b43921c14.png)

**Comment by jcalcada-atoswap** [comment]
I also use a VM ... I'm going to try tp re install my VM and build again the project.
Thank you for your time
