### ISSUE TITLE
Compile Debian on Windows.

### ISSUE THREAD

**Issue by dephraiim** [electron-userland/electron-installer-debian#233]
I get this for Windows Installation.

`npm install -g electron-installer-debian`

```bash
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for electron-installer-debian@3.1.0: wanted {"os":"darwin,linux","arch":"any"} (current:{"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

Is there a work aroud?
I don't have a VM.

**Comment by malept** [comment]
Either install [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/), or Use a CI provider like GitHub Actions or Travis CI.
