### ISSUE TITLE
Error: could not find the Electron app binary at "dist/app-linux-x64/lumzapp-electron". You may need to re-bundle the app using Electron Packager's "executableName" option

### ISSUE THREAD

**Issue by heyimgab** [electron-userland/electron-installer-debian#252]
Error: could not find the Electron app binary at "dist/app-linux-x64/lumzapp-electron". You may need to re-bundle the app using Electron Packager's "executableName" option

**Comment by malept** [comment]
Duplicate of #198

**Comment by cjm-korea** [comment]
I also experienced this error. I posted how to fix the error after a lot of trial and error.

https://it-jm.tistory.com/187
