### ISSUE TITLE
[feature] Upload to PPA (launchpad) docs

### ISSUE THREAD

**Issue by jgresham** [electron-userland/electron-installer-debian#348]
This is a request for docs or any helpful advice for uploading and maintaining an electron app through a ppa like launchpad.

It looks like the Launchpad docs say `dput` looks for a `.changes` file when uploading. Is this something that that could be output by the deb maker? I know `.deb` isn't directly uploaded to the ppa, but it seems like the logic for ppa would go here.

**Comment by malept** [comment]
This feels like a publisher plugin for Electron Forge, rather than something in this package.
